### ISSUE TITLE
Submission to flathub

### ISSUE THREAD

**Issue by andrewgdunn** [yktoo/ymuse#12]
would it be possible to add submission to flathub as a release mechanism?

This project is fantastic!

**Comment by yktoo** [comment]
Making a flatpak looks like a substantial time investment to me whereas I'm not sure there's really a demand for this.

I don't think I'll pick this up any time soon but I'm open to external contributions.

**Comment by tidux** [comment]
I'd say there's at least moderate demand for this.  Right now there are zero mpd clients on Flathub, and Cantata is in maintenance mode.  The only mpd clients available on my current distribution are either TUIs or web interfaces.  Publishing to Flathub would fill an empty niche in the ecosystem.

**Comment by storrgie** [comment]
if there was a financial prioritization mechanism I'd pledge for this!

**Comment by yktoo** [comment]
Resolved via https://github.com/flathub/flathub/pull/3226.
