### ISSUE TITLE
Document steps to copy icons when running from source tree

### ISSUE THREAD

**Issue by mad-ady** [yktoo/ymuse#13]
Please add to the documentation that the icons need to be copied like this:
```
sudo cp resources/icons/hicolor/* /usr/share/icons/gnome/
```
Otherwise they are not drawn correctly.
Thanks!

**Comment by yktoo** [comment]
I guess you mean running the app from source here.

I have a remark in this respect. I don't think `/usr/share/icons/gnome` is the correct path for custom icons. As the source folder's name suggests, they're supposed to land in `/usr/share/icons/hicolor`, which is the default icons folder in X. Also, a subsequent icon cache update would make sense.

I'll extend the docs with the necessary steps.

**Comment by mad-ady** [comment]
I had to use strace to see where it would look for icons, and I saw it was looking for them at /usr/share/icons/gnome/ (among other locations), so that's why I copied them there. But yes, a mention in the docs would be nice, thanks!
