### ISSUE TITLE
decode error

### ISSUE THREAD

**Issue by dln949** [yktoo/ymuse#14]
Ymuse 0.15 on Ubuntu 18.04.5

I am able to connect to the remote mpd server, I am able to navigate among all the audio files in the server's file structure in the "Library" tab, and I am able to add a song from the "Library" tab to the "Queue" tab.  

When I try to play a file, I get an error that it could not play it because there is a "decoding" error.  

I don't know what this error message means, and I don't know what I should do in response.  

The audio files are mp3 files, they play fine on a number of audio applications (vlc, smplayer, others, etc.).

**Comment by yktoo** [comment]
Can you run Ymuse with `-vv` and attach the error logs?

**Comment by dln949** [comment]
I don't know where the "error log" file is located.  Is what you wanted the output in the terminal?  If that is what you wanted, here it is:  

> main1@system1:~$ ymuse -vv
2020/09/08 10:47:02 10:47:02.608 INFO  main Ymuse version v0.15; f236bc20a296c9eed88847c67e02683bf259f063; released 2020-09-06T13:37:09+00:00
2020/09/08 10:47:02 10:47:02.673 DEBUG config Loaded configuration from /home/main1/snap/ymuse/31/.config/ymuse/config.json
2020/09/08 10:47:02 10:47:02.902 DEBUG player MainWindow.onMap()
2020/09/08 10:47:02 10:47:02.905 DEBUG player connect()
2020/09/08 10:47:02 10:47:02.905 DEBUG player watch()
2020/09/08 10:47:02 10:47:02.905 DEBUG player Connecting to MPD (network=tcp, address=192.168.1.19:6602)
2020/09/08 10:47:02 10:47:02.906 DEBUG player Start watcher
2020/09/08 10:47:03 10:47:03.074 DEBUG player Current track: mpd.Attrs{"Bitrate":"", "Format":""}
2020/09/08 10:47:03 10:47:03.250 DEBUG player Current track: mpd.Attrs{"Bitrate":"", "Format":""}
2020/09/08 10:47:15 10:47:15.063 DEBUG player onSubsystemChange(playlist)
2020/09/08 10:47:15 10:47:15.067 DEBUG player Current track: mpd.Attrs{"Bitrate":"", "Format":""}
2020/09/08 10:47:20 10:47:20.806 DEBUG player onSubsystemChange(player)
2020/09/08 10:47:20 10:47:20.807 DEBUG player Current track: mpd.Attrs{"Album":"noalbum", "AlbumArtist":"311", "Artist":"311", "Bitrate":"", "Format":"", "Genre":"(17)", "Id":"40", "Last-Modified":"2016-06-13T05:21:51Z", "Pos":"0", "Time":"207", "Title":"Amber", "duration":"207.281", "file":"311/noalbum/311 - Amber.mp3"}

**Comment by yktoo** [comment]
Yes there's only one log, which is output to the console. I, however I

**Comment by dln949** [comment]
At the bottom of the ymuse window, see attached screenshot for an example.

![Screenshot from 2020-09-08 10-56-57](https://user-images.githubusercontent.com/8601150/92500052-3b5b2580-f1c2-11ea-8dd8-fbc69310658e.png)

**Comment by yktoo** [comment]
Weird that it isn't visible in the log. Does this file play if you use another MPD client?

**Comment by dln949** [comment]
Just out of desperation, I did a rescan of the library.  That seemed to fix the problem - It seems that originally, somehow Ymuse had that particular song as being located in the wrong directory.  After the rescan, now the directories look "fixed" in Ymuse, and I no longer get the decode error.  

However.....  

Now that I am able to "play" songs, I have a different problem - no audio.  I click on the play button, and I see the seconds increase indicating the song is being played, but I hear nothing - and the timer indicator does not move along the path, it is stuck in the middle position, even though the seconds are going by.  

How do I track down that problem?  Do you want me to make this a new issue?

**Comment by yktoo** [comment]
This looks like a different problem indeed.

I'd recommend trying things out with another MPD client (mpc, Sonata, Cantata or any other). If the problem persists with another client, it means it's caused by MPD self (perhaps misconfiguration) and not by the client.
