### ISSUE TITLE
No Audio

### ISSUE THREAD

**Issue by dln949** [yktoo/ymuse#15]
Ymuse 0.15 (snap package), Ubuntu 18.04.5.  

Songs in the "Queue" tab "play", but there is no audio, and the pointer does not move from the middle position.  The seconds do change, indicating the song is silently playing.  

Connecting to the exact same mpd server using the "Gnome Music Player" mpd client, I can play the exact same song on the same computer, and the audio works fine.

**Comment by yktoo** [comment]
Is there any error or warning in the log?

**Comment by dln949** [comment]
Here is the log output while the song is silently playing (and, Yes, the volume is up, when I play other audio on this computer I can hear it):  

> main1@system1:~$ ymuse -vv
2020/09/08 13:11:55 13:11:55.539 INFO  main Ymuse version v0.15; f236bc20a296c9eed88847c67e02683bf259f063; released 2020-09-06T13:37:09+00:00
2020/09/08 13:11:55 13:11:55.603 DEBUG config Loaded configuration from /home/main1/snap/ymuse/31/.config/ymuse/config.json
2020/09/08 13:11:55 13:11:55.831 DEBUG player MainWindow.onMap()
2020/09/08 13:11:55 13:11:55.834 DEBUG player watch()
2020/09/08 13:11:55 13:11:55.834 DEBUG player connect()
2020/09/08 13:11:55 13:11:55.835 DEBUG player Connecting to MPD (network=tcp, address=192.168.1.19:6602)
2020/09/08 13:11:55 13:11:55.836 DEBUG player Start watcher
2020/09/08 13:11:55 13:11:55.846 DEBUG player Current track: mpd.Attrs{"Bitrate":"", "Format":""}
2020/09/08 13:11:55 13:11:55.853 DEBUG player Current track: mpd.Attrs{"Bitrate":"", "Format":""}
2020/09/08 13:12:06 13:12:06.270 DEBUG player onSubsystemChange(playlist)
2020/09/08 13:12:06 13:12:06.273 DEBUG player Current track: mpd.Attrs{"Bitrate":"", "Format":""}
2020/09/08 13:12:13 13:12:13.545 DEBUG player onSubsystemChange(player)
2020/09/08 13:12:13 13:12:13.546 DEBUG player onSubsystemChange(player)
2020/09/08 13:12:13 13:12:13.593 DEBUG player Current track: mpd.Attrs{"Album":"noalbum", "AlbumArtist":"311", "Artist":"311", "Bitrate":"224", "Format":"44100:24:2", "Genre":"(17)", "Id":"45", "Last-Modified":"2019-11-28T04:19:53Z", "Pos":"0", "Time":"236", "Title":"Hey You", "duration":"235.833", "file":"311/noalbum/311 - Hey You.mp3"}
2020/09/08 13:12:13 13:12:13.609 DEBUG player Current track: mpd.Attrs{"Album":"noalbum", "AlbumArtist":"311", "Artist":"311", "Bitrate":"224", "Format":"44100:24:2", "Genre":"(17)", "Id":"45", "Last-Modified":"2019-11-28T04:19:53Z", "Pos":"0", "Time":"236", "Title":"Hey You", "duration":"235.833", "file":"311/noalbum/311 - Hey You.mp3"}

**Comment by yktoo** [comment]
I personally doubt it has anything to do with Ymuse. Ymuse is just a client, which sends a "play" command to MPD. It knows nothing about files (beyond the URIs reported by MPD), audio outputs, formats etc.

I'd suggest pinning the problem down by trying, for example (requires `mpc` to be installed):
```bash
mpc pause
mpc play
```

**Comment by dln949** [comment]
Ymuse is the only application that I have an audio problem with, but you know these kinds of things better than I, so I will take your word for it when you say that you do not think the problem lies with Ymuse.  

Regarding your suggestion, I was not clear on something:  *WHEN* should I enter those two commands?  While attempting to play an audio file via Ymuse?

**Comment by yktoo** [comment]
1. Make sure the MPD queue contains an audio file and MPD is not playing
2. Quit Ymuse altogether
3. Issue the `mpc play` command. MPD should start playing, but Ymuse isn't involved.

Does it play like this? What happens if you start playback from Ymuse instead?

And last but not least: does it concern the same MPD instance, e.g. running on `localhost`?

**Comment by dln949** [comment]
Thanks for hanging in there with me.  

Before I try what you said, I need to ask you a question.  

I have the mpd server running on computer A.  

I am connecting to that server using Ymuse running on computer B.  Computer B does NOT have mpd nor mpc installed.  

Do I need mpd and/or mpc installed on computer B for Ymuse to be able to play music served by mpd from computer A?  

What made me think of this is your latest message, when you wrote, "Issue the mpc play command", I wasn't sure which computer you meant for me to issue that command on.

**Comment by yktoo** [comment]
`mpc` is just another MPD client, like Ymuse. You run it on the control machine (computer B in your example), just like Ymuse.

What's important in this setup though is that you connect to and control the right MPD instance (computer A), which you configure in Ymuse's preferences, or, in the case of `mpc`, using the `--host=...` command-line option.

More generally, it doesn't matter at all on which machine you run your client as long as it connects to the correct MPD instance, which could be anywhere on the network.

**Comment by dln949** [comment]
Ok, thank you again, I will try what you are suggesting.  Before I do that, I just want to understand something:  

As I indicated earlier in this issue thread, using a different mpd client (Gnome Music Player) on computer B and connecting to the mpd server on computer A - same set up as Ymuse - I am able to play the audio files and the sound works just fine.  So, since mpc is just another mpd client, what will your suggested test of using mpc tell us that we cannot conclude from my successful use of Gnome Music Player?

**Comment by yktoo** [comment]
Is this issue still relevant?

**Comment by dln949** [comment]
> Is this issue still relevant?

yes

**Comment by yktoo** [comment]
Sorry for not responding to your last question. I'm not familiar with Gnome Music Player so I cannot say for sure what and how you're playing using that.

`mpc`, on the other hand, is a straightforward single-purpose command-line tool which should make identifying the problem somewhat easier. Did you give it a try?

**Comment by dln949** [comment]
Yes, I had attempted mpc.  Unfortunately, I was unable to figure out the mpc commands, so I was not even able to tell mpc how to "find" the mpd host.  So, I was not able to perform a fair test of mpc.

**Comment by yktoo** [comment]
Some examples:
```bash
mpc --host=localhost play
mpc --host=localhost pause
```

You'll need to replace `localhost` with the name of the computer running MPD (if it's running elsewhere).

**Comment by dln949** [comment]
Well....  no joy.  

I've attached a screeshot from the host (system19) showing that mpd is running.  

On the client machine, here is what I get:  

main1@system1:~$ mpc --host=system19 play
mpd error: Failed to resolve host name
![Screenshot from 2021-02-08 13-07-53](https://user-images.githubusercontent.com/8601150/107269413-30295180-6a0f-11eb-83df-bfa2c559967e.png)

**Comment by yktoo** [comment]
Well, "inactive" suggests it isn't running. But in order to get sensible info, you should either run `sudo systemctl status mpd` (if MPD is running system-wide) or `systemctl --user status mpd` (if it's running in your account).

Also, you'll be better off if you specify the host machine's IP address after `--host=` instead of hostname (which is apparently fails to resolve).

**Comment by dln949** [comment]
Now I get this (no sound) on the client machine:  

main1@system1:~$ mpc --host=192.168.1.19 play
311 - Creatures (For A While)
[playing] #1/2   0:00/4:27 (0%)
volume: n/a   repeat: off   random: off   single: off   consume: off

**Comment by yktoo** [comment]
Okay, so it is playing, but there's no sound. This most likely means your MPD setup is incomplete or incorrect. Perhaps reading the [manual](https://www.musicpd.org/doc/html/user.html#configuring-audio-outputs) is worth a try.

This also confirms my initial guess the problem is with MPD and not with the client. The client is only telling MPD to start/stop playback etc.

**Comment by dln949** [comment]
I think you are right, something funny with my mpd setup.
