### ISSUE TITLE
[Feature request] Smooth scroll behavior setting

### ISSUE THREAD

**Issue by xuijuthub** [yktoo/ymuse#18]
. An option to toggle on/off.

**Comment by yktoo** [comment]
I'm not sure if that's possible on the application level, but perhaps [can be done system-wide](https://askubuntu.com/questions/903160/turn-off-smooth-scrolling-in-gtk3). Will this work for you?

**Comment by yktoo** [comment]
Closing for now, please reopen if still relevant.
