### ISSUE TITLE
building v0.15 from source: icons do not load

### ISSUE THREAD

**Issue by xuijuthub** [yktoo/ymuse#19]
Menu, playback, etc. icons do not load.
They are copied in place.
On some OS update-icon-caches has gtk- prefix:
> update-icon-caches /usr/share/icons/hicolor/*

returns
> -su: update-icon-caches: command not found

then
>gtk-update-icon-cache /usr/share/icons/hicolor/*

returns
>gtk-update-icon-cache: No theme index file.

 I try to run gtk-update-icon-cache, it's version is 3.24.21
tried
>gtk-update-icon-cache -t /usr/share/icons/hicolor/*
> gtk-update-icon-cache

^ both executed successfully, but did not help.

**Comment by yktoo** [comment]
What OS and DE do you run?

**Comment by xuijuthub** [comment]
Gentoo (linux), no desktop environment, just openbox.
After restart it works. But there ought to be a better way.

**Comment by yktoo** [comment]
Kinda hard for me to say as I'm not using Gentoo. From `gtk-update-icon-cache`'s [manpage](https://linux.die.net/man/1/gtk-update-icon-cache) I can conclude it expects an `index.theme` file at the specified directory. So my guess would be:

```bash
gtk-update-icon-cache /usr/share/icons/hicolor
```

(provided `/usr/share/icons/hicolor/index.theme` exists)

**Comment by sdoconnell** [comment]
Use the `-t` option:

    $ sudo gtk-update-icon-cache -t /usr/share/icons/hicolor/
    gtk-update-icon-cache: Cache file created successfully.

From `--help` for `gtk-update-icon-cache`:

      -t, --ignore-theme-index     Don't check for the existence of index.theme

**Comment by yktoo** [comment]
Could you please verify the proposed solution and reopen if the problem persists?
