### ISSUE TITLE
[Feature Request] Play http stream from remote server

### ISSUE THREAD

**Issue by dayfuaim** [yktoo/ymuse#22]
Ymuse is great app for MPD. :)

I have mpd running on next local network machine and it outputs the httpd stream.

Please make the possibility to play httpd stream.

**Comment by yktoo** [comment]
What do you mean with "httpd stream"? Is the existing stream functionality niet sufficient for your goals?

**Comment by dayfuaim** [comment]
I mean the following.

MPD is running at one computer, but I want to listen the stream from another one.
MPD is configured like this:
```
audio_output {
    type            "httpd"
    name            "My HTTP Stream"
    encoder         "lame"          # vorbis/lame
    port            "6800"
    bitrate         "320"
    format          "44100:24:2"
}
```

If I simply connect to MPD, I don't hear any sound.

**Comment by yktoo** [comment]
As far as I'm concerned, it's purely the MPD's configuration that has nothing to do with the client. To be honest I don't quite understand what is expected of Ymuse to support this.

**Comment by yktoo** [comment]
@dayfuaim Did you manage to achieve HTTP streaming by means of MPD configuration?

**Comment by dayfuaim** [comment]
@yktoo Yes, kind of.
Now I close this issue.

**Comment by curiousercreative** [comment]
@yktoo sorry to bug you here, but hoping you can help. Does Ymuse support streaming from a remote mpd server? I'm new to mpd, but I've got a server running and outputting an HTTP stream that I can play from VLC for example (remote server port 8000). I thought consume mode was maybe a toggle for that, but it didn't seem to do anything.

I've got the latest flatpak installed, running on Pop! 22.04.

**Comment by yktoo** [comment]
@curiousercreative Ymuse is merely a frontend to MPD. I'm not sure what you mean with "streaming from a remote mpd server." Ymuse can connect to any remote MPD server reachable via TCP, to **control** it.

**Comment by curiousercreative** [comment]
@yktoo ok, thanks for clarifying. There's an Android client MAPD that supports streaming the http audio output (in addition to controlling) that is nice and I'm looking for a similar solution for the desktop.
