### ISSUE TITLE
[Feature Request] Option for hiding the Queue toolbar

### ISSUE THREAD

**Issue by rare-magma** [yktoo/ymuse#23]
Hi,

First of all thank you for building this tool!

I'd like to suggest creating the possibility of hiding the playlist control bar. 
Personally I don't use them often and would enjoy the cleaner look.

Cheers

**Comment by yktoo** [comment]
What do you mean exactly with "playlist control bar"? The application toolbars?

**Comment by rare-magma** [comment]
I mean the toolbar with the clear play queue icon, remove selected tracks icon, etc
