### ISSUE TITLE
[Feature request] MPRIS support

### ISSUE THREAD

**Issue by Mel34** [yktoo/ymuse#24]
MPRIS is a standard D-Bus interface which aims to provide a common programmatic API for controlling media players.

**Comment by yktoo** [comment]
Did you consider using [mpDris2](https://github.com/eonpatapon/mpDris2) for that? I believe supporting it at the MPD level is a better option because it works with any client (and event without one).

**Comment by Mel34** [comment]
Oh that's clever, I'll look into that. Thank you!

**Comment by Mel34** [comment]
BTW Have you tried mpd-mpris? It's also written in GO.

**Comment by yktoo** [comment]
No I haven't, I've always been using mpDris2, which does its job pretty decently (although not without rare crashes ).

Perhaps I'll give mpd-mpris a try. Funny that it's using the same `gompd` lib as Ymuse.
