### ISSUE TITLE
Ymuse floods system logs if mpd connection disappears

### ISSUE THREAD

**Issue by ryan-sg** [yktoo/ymuse#26]
Loving this mpd client, very clean and nice!  I accidentally had my /var fill up due to playing with changing the mpd config file as such:

Jan 31 13:19:58 iddqd ymuse.desktop[376864]: 2021/01/31 13:19:58 13:19:58.644 WARNING player Watcher error write tcp 192.168.8.129:34118->192.168.8.132:6600: write: broken pipe

I have millions of these, and since I have nvme it filled pretty quickly :laughing:

I imagine its just the autoreconnect being stupid fast on my system, maybe some throttling is in order?

**Comment by yktoo** [comment]
Agreed, needs a fix.
