### ISSUE TITLE
Error: too many colons in address (IPv6 support)

### ISSUE THREAD

**Issue by ivan-avalos** [yktoo/ymuse#28]
When I try to write an IPv6 address, it gives that error. When I add `[]` to the address, it stops responding.

**Comment by yktoo** [comment]
Can you provide a complete stack trace (or any other relevant details)?

**Comment by ivan-avalos** [comment]
Sorry, my MPD server was down when I tried with '[]', but still, the app shouldn't stop responding if it can't connect to the server.

**Comment by yktoo** [comment]
I concur. Perhaps a duplicate of #26?
