### ISSUE TITLE
Slow response with album art enabled and queued streams

### ISSUE THREAD

**Issue by jvandenbroek** [yktoo/ymuse#30]
When album art is enabled, Ymuse start and navigation is slow, especially when multiple radio streams are in queue. Mpd log displays multiple curl 404 fetch errors, so it seems to pause on that check. Maybe simply disable album art for streams is a solution? I'd like to keep it enabled for the rest of my library.

**Comment by yktoo** [comment]
Can you confirm MPD doesn't try to fetch stream covers when you disable **Show album art** in Preferences?

**Comment by jvandenbroek** [comment]
Yes, I've disabled it for now and no curl fetch errors appear in mpd log and no longer hanging delays.
