### ISSUE TITLE
using Ymuse with Conky

### ISSUE THREAD

**Issue by dln949** [yktoo/ymuse#32]
(Not sure if this is an appropriate place to post this question, if not, say so, I certainly will understand.)

Ymuse 0.16, Ubuntu 18.04

I'm trying to figure out how to display status information about what Ymuse is playing in Conky.  

I currently have a conky file set up for a different audio application - Goodvibes.  Below I show the conky instructions for Goodvibes, and what the display looks like.  I would like to replicate this for Ymuse, but I don't know how to do that.  Would someone here know how I would need to alter the entries in the file I have for Goodvibes in order to make it work for Ymuse?  

Conky file instructions for Goodvibes:  

conky.text = [[
${if_match "${execi 3 qdbus org.mpris.MediaPlayer2.Goodvibes /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlaybackStatus 2>/dev/null}" == "Playing"}
${color2}Goodvibes Info
Station:  ${color0}${execpi 3 qdbus org.mpris.MediaPlayer2.Goodvibes /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Metadata 2>/dev/null | grep "^goodvibes:station:" | cut -d':' -f3-}
${color2}Artist - Track:  ${color0}${execpi 3 qdbus org.mpris.MediaPlayer2.Goodvibes /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Metadata 2>/dev/null | grep "^xesam:title:" | cut -d':' -f3-}
${else}
${color2}Goodvibes is not playing.${color0}
${endif}
${color2}Volume amixer 1 (0 - 64):  ${color0}${exec amixer -c 1 get Master | grep Mono:}
${color0}                  ${execbar amixer -c 1 get Master | grep -o -E '[0-9]{2}' | head -n3 | tail -n1}
${color2}Volume amixer 2 (0 - 64):  ${color0}${exec amixer -c 2 get Master | grep Mono:}
${color0}                  ${execbar amixer -c 2 get Master | grep -o -E '[0-9]{2}' | head -n3 | tail -n1}
]]

![Screenshot from 2021-02-15 20-01-23](https://user-images.githubusercontent.com/8601150/108009922-5596fc00-6fc9-11eb-9b96-5e7d663fbbba.png)

**Comment by yktoo** [comment]
Yet again, Ymuse is only a graphical front-end to MPD, whereas what you want here is integration with MPD (most likely involving the `mpc` tool). I suggest asking that either on Conky or MPD forum.
