### ISSUE TITLE
./ymuse: undefined symbol: gdk_subpixel_layout_get_type

### ISSUE THREAD

**Issue by kandeshvari** [yktoo/ymuse#35]
No special dependencies in README file but I got subj on start :(

ubuntu 16.04
libgtk-3-0:amd64 3.18.9-1ubuntu3.3

**Comment by yktoo** [comment]
Under what circumstance did that happen? Is it by any chance related to showing album artwork?

**Comment by kandeshvari** [comment]
It happens just on start

```
$ ymuse
ymuse: symbol lookup error: ymuse: undefined symbol: gdk_subpixel_layout_get_type
```
I suppose there is minimum gtk version requirement.

**Comment by yktoo** [comment]
Indeed. Apparently, Ymuse is now implicitly dependent on GTK 3.22 (via gotk3 [GDK bindings](https://github.com/gotk3/gotk3/blob/16a74fbac4f12b38c324b8bf4a565b18c04bcd46/gdk/gdk_since_3_22.go#L34)).

**Comment by yktoo** [comment]
I guess installing Ymuse from snap would be a solution, could you try that?

**Comment by kandeshvari** [comment]
too sad :( 

snap is not my choice. It would be great if you'll think about releasing AppImage along with snap.
