### ISSUE TITLE
ymuse-bin in AUR

### ISSUE THREAD

**Issue by vestingz** [yktoo/ymuse#40]
Hi,

thanks for this nice piece of software - I really like it! :)

I made an AUR package based on your .deb binary package here: https://aur.archlinux.org/packages/ymuse-bin/
Maybe you want to include it on your website/README in the download/install section.

Sorry to abuse this issue tracker; the contact form on your website seems to be broken and I was not able to locate your email address.

Have a good weekend!
Emilio

**Comment by yktoo** [comment]
Thanks Emilio, that's nice of you. Do contact me if you face issues with the contact form (I could find any). My email is mentioned at every single commit :)

**Comment by vestingz** [comment]
You're welcome; I hope many people will find and use ymuse, so that was
the least I could do :)

> Do contact me if you face issues with the contact form (I could
> find any).

I wish I had documented the error properly; now I don't have any 
recollection what went wrong that time. Sorry!

> My email is mentioned at every single commit :) 

Yeah, now that you say I also see it :D
