### ISSUE TITLE
[Feature Request] MPD Output toggle

### ISSUE THREAD

**Issue by imsamuka** [yktoo/ymuse#44]
I would love to have a way to toggle different MPD outputs on and off. It is possible to do it in 'ncmpcpp' and 'M.A.L.P' clients, and it is a very useful feature to have.

Example from M.A.L.P:

![MALP Example](https://i.imgur.com/1Yc8xHm.png)

I suggest to do it in the "..." dropdown, something like this:

![Dropdown Example](https://i.imgur.com/winIL4x.png)

I use the Ymuse primarily, so i will refrain myself to do complex sound outputs in MPD for now. Thanks for the amazing work!

**Comment by yktoo** [comment]
Thanks for the suggestion, this is implemented in a separate dialog (accessible via the player menu or with <kbd>Ctrl</kbd><kbd>O</kbd>).
