### ISSUE TITLE
Sort entries on the Streams tab ignoring case

### ISSUE THREAD

**Issue by dln949** [yktoo/ymuse#45]
Snap version of Ymuse 0.18 running on Ubuntu Bionic.  

I have a long list of stations in the "Streams"  tab.  When I add a station, it goes to the bottom of the list.  How do I sort the stations alphabetically?  I can't figure out how to do that.  Now it is very difficult for me to find a station because I have to look through the entire list.

**Comment by yktoo** [comment]
Actually they are always sorted alphabetically, by the stream name. Isn't that the case with you?

**Comment by dln949** [comment]
It is not the case for me, please see the attached screenshot.  
![Screenshot from 2022-02-16 14-02-03](https://user-images.githubusercontent.com/8601150/154346435-839be6ba-0b38-4f1d-b5c3-9f832402d7b5.png)

**Comment by yktoo** [comment]
Well, it actually **is** the case, only the sorting is case-sensitive :-) So, it goes `A` ⇒ `Z` ⇒ `a` ⇒ `z`.

**Comment by dln949** [comment]
Ohhhhh........  I see.......

**Comment by yktoo** [comment]
I think it'd be a good idea to make it case-insensitive though.
