### ISSUE TITLE
A particular stream will not play

### ISSUE THREAD

**Issue by dln949** [yktoo/ymuse#47]
Ymuse 0.19 on Ubuntu 18.04

I am trying to play this stream: http://stream.open.fm/68 I get no error message at all, just silence.  But, this stream plays fine on other music/audio applications.  And, other streams play just fine in Ymuse.  

How do I track down why Ymuse will not play this particular stream?  Thanks.

**Comment by yktoo** [comment]
It does play for me, but in a poor quality (42 kbps).

You first need to figure out whether it's a problem in MPD or Ymuse. For the former that you can check MPD logs, for the latter start Ymuse in the console:

```bash
ymuse -vv
```

**Comment by dln949** [comment]
I see this in the mpd logs:  

"faad_decoder: error decoding AAC stream: Unexpected channel configuration change"

not at all sure what that is telling me......  

Appears not to be a ymuse problem.

**Comment by yktoo** [comment]
Might be a decoder issue, you can try to google it.
