### ISSUE TITLE
[Feature Request] Move categories around in queue

### ISSUE THREAD

**Issue by ShadiestGoat** [yktoo/ymuse#49]
It would be nice if you could move these categories around in the queue view. 

![image](https://user-images.githubusercontent.com/48590492/169259807-a4fae5ce-3652-4f1a-a45e-2aac70e8c7fc.png)

For example, say I want the first thing to be visible would be the title of the song.

**Comment by yktoo** [comment]
You can change this in Preferences ⇒ Columns (use the up/down buttons at the bottom).
