### ISSUE TITLE
No support for seek in current track?

### ISSUE THREAD

**Issue by dunrix** [yktoo/ymuse#56]
Nice feature in `mpc`, and `gmpc` before it has been abandoned, was ability to skip forward & backward by given amount of time in a current playback.

Any intention to add it to `ymuse` including appropriate keyboard bindings and clickable buttons? With possible preference option to set size of this time step? With something like 5 seconds by default.

**Comment by yktoo** [comment]
Hi @dunrix, looks like a worthy addition indeed.

I'll add a configurable seek action, with <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>←</kbd> and <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>→</kbd> as shortcuts. I don't think adding buttons is necessary though as it's a relatively rarely needed function and I want to keep the UI straight and clean.

**Comment by yktoo** [comment]
The seek duration in seconds can be configured in Ymuse config file (`~/.config/ymuse/config.json`) in the `PlayerSeekDuration` parameter. This setting is not (yet) available in the UI.

**Comment by dunrix** [comment]
@yktoo Great, thanks for hearing me out! Now I can stick with ymuse for a long time. Good job.
