### ISSUE TITLE
error message I cannot decipher

### ISSUE THREAD

**Issue by dln949** [yktoo/ymuse#57]
Ymuse 0.20 running on Ubuntu 18.04.  

Ymuse is able to find the library of songs on the remote computer on which mpd is running.  Until recently it worked fine, but now when I try to play a song, the playing progress indicator doesn't move, there is no audio, and Ymuse shows this error message:  

(no track) - Failed to decode /path/to/song; Failed to open /path/to/song

But I don't know what that message is telling me, what it means that I should be looking into.  

Can you interpret this message for me?  Thanks.

**Comment by yktoo** [comment]
I've a strong suspicion the message originates from the MPD, so I'd examine MPD logs first.
