### ISSUE TITLE
Icons missing in interface

### ISSUE THREAD

**Issue by vext01** [yktoo/ymuse#58]
Hi,

I was looking for a replacement for cantatata, which is now deprecated. ymuse looks nice.

I installed using `go install` and it built fine, but the UI is missing all of it's icons for some reason:

![image](https://user-images.githubusercontent.com/604955/185085478-608960d0-d5af-4e99-973c-c0cd3691c019.png)

This is under xfce4 on OpenBSD. I tried changing icon theme, but no cigar.

Any idea why this may be?

**Comment by vext01** [comment]
This may be related?

```
2022/08/17 10:25:28 10:25:28.819 WARNING player Failed to restore library path: failed to unmarshal library path element: missing prefix
```

**Comment by yktoo** [comment]
@vext01 the mentioned warning isn't related. In order to get icons you'll need to execute the step 4 of the [README](https://github.com/yktoo/ymuse) thus copying the resources (you'll need the source files for that):

```bash
4. Copy over the icons and localisations:

sudo cp -r resources/icons/* /usr/share/icons/
sudo cp -r resources/i18n/generated/* /usr/share/locale/
sudo update-icon-caches /usr/share/icons/hicolor/*
```

**Comment by vext01** [comment]
OK. I plan to package this for OpenBSD, so I think rather than pollute my `/usr`, I'll just start packaging.

Thanks
