### ISSUE TITLE
Add bitrate and audio format display

### ISSUE THREAD

**Issue by yktoo** [yktoo/ymuse#6]
This is only reported by MPD for the currently played track.

**Comment by yktoo** [comment]
Pushed to `dev`; attributes can be made visible by adding the following snippet to the player title template (in Preferences):
```html
<small>{{ .Format }} • {{ .Bitrate }}kbps</small>
```

It will then look like this:
![image](https://user-images.githubusercontent.com/1675911/86365813-4a7d9e80-bc7a-11ea-89d9-283a973d54e9.png)

**Comment by pierreTPE57** [comment]
Nice feature. MPD still doesn't seem to know well DSD format. A stereo SACD iso is displayed dsd64:2 • 75kbps while Foobar2000 says it's 5645 kbps, which is closer to reality !
