### ISSUE TITLE
Debian submission

### ISSUE THREAD

**Issue by mdosch** [yktoo/ymuse#62]
Dear Dmitry,

can you please clarify which metadata is covered by CC0 according to https://github.com/yktoo/ymuse/blob/dev/resources/metainfo/com.yktoo.ymuse.metainfo.xml#L4

Is this about the the file com.yktoo.ymuse.metainfo.xml itself only or are the icons also CC0?

**Comment by yktoo** [comment]
I'm personally not so much into the legal, but my take on that is the icons are a constituent part of the app, so the Apache 2.0 license applies.

**Comment by mdosch** [comment]
Thank you for the quick reply. Then I think this should be alright: https://salsa.debian.org/go-team/packages/ymuse/-/blob/debian/sid/debian/copyright

**Comment by yktoo** [comment]
Yes, looks good! Thanks for working on the Debian packaging for Ymuse, is it expected to land in official Debian repos?

**Comment by mdosch** [comment]
That's what I am targeting at, but I can't give a guarantee. :)

**Comment by mdosch** [comment]
It entered unstable: https://tracker.debian.org/pkg/ymuse

**Comment by yktoo** [comment]
Great, thanks @mdosch! Could you please track its progress here so that everyone interested is up to date?

**Comment by mdosch** [comment]
Yes, of course. At least until it arrives in a stable release (I assume 
it will be in bookworm which should be released next year).

**Comment by mdosch** [comment]
Some update:
[Ymuse landed in Ubuntu](https://launchpad.net/ubuntu/+source/ymuse), so it should be part of 23.04.
[German translation about to hit Debian](https://tracker.debian.org/news/1396562/accepted-ymuse-021git20221209981861c-1-source-into-unstable/).

**Comment by yktoo** [comment]
Yaaaay!
![Celebrate!](https://user-images.githubusercontent.com/1675911/206734990-5f672c71-6efa-4c30-b473-5e00278694a5.gif)

**Comment by mdosch** [comment]
Yesterday Debian 12 "Bookworm" got released and ships ymuse.  🎉

**Comment by yktoo** [comment]
Awesome, thanks @mdosch !

A question: how will it work in case op updates? What will I need to do in order to make them available?

**Comment by mdosch** [comment]
If you tag releases I will update the package for Debian Unstable and 
they will migrate to Debian Testing. For Debian Stable there are no 
version updates only security fixes.
