### ISSUE TITLE
Metainfo icon type invalid

### ISSUE THREAD

**Issue by mdosch** [yktoo/ymuse#66]
Dear Dmitry,

`appstreamcli validate` reports the type `local` as invalid. 

```
LANG=en_US.UTF8 appstreamcli validate resources/metainfo/com.yktoo.ymuse.metainfo.xml
E: com.yktoo.ymuse:10: metainfo-invalid-icon-type local

✘ Validation failed: errors: 1
```

I am not fully sure about this sentence from the [appstream docs](https://www.freedesktop.org/software/appstream/docs/chap-CollectionData.html#tag-ct-icon):

> local icons are reserved for AppStream data installed by local applications or via 3rd-party application installers. They should specify a full file path.

Maybe using `<icon type="remote">https://raw.githubusercontent.com/yktoo/ymuse/dev/resources/icons/hicolor/scalable/apps/com.yktoo.ymuse.svg</icon>` would be better? At least this validates successfully. What do you think?

**Comment by yktoo** [comment]
Indeed.

```
$ appstreamcli validate --explain resources/metainfo/com.yktoo.ymuse.metainfo.xml 
E: com.yktoo.ymuse:10: metainfo-invalid-icon-type local
   Metainfo files may only contain icons of type `stock` or `remote`, the set type is not allowed.

✘ Validation failed: errors: 1
```

Will look into it.
