### ISSUE TITLE
Media keys support

### ISSUE THREAD

**Issue by topas-rec** [yktoo/ymuse#67]
I just recognised that the media keys of my keyboard don't seem to control Ymuse.
I that expected behavior?

I'm on arch and Gnome.

**Comment by yktoo** [comment]
Yes, unless you have [mpDris2 installed](https://yktoo.com/en/software/ymuse/faq/#can-i-assign-media-buttons-on-my-keyboard-to-control-ymuse).

**Comment by topas-rec** [comment]
Oh I missed the FAQ. Thanks.
