### ISSUE TITLE
Making it usable in MacOS (improvement)

### ISSUE THREAD

**Issue by LordMyschkin** [yktoo/ymuse#77]
Because there are very few mpd-clients for MacOS, I tried compiling and running it; to my surprise, ymuse runs after compiling from source with a very small mileage - but it it just not possible to copy the resources to /usr/share, because that is (even sudoed) a read only filesystem. 
If you just made the location of the resources configurable, using ymuse on MacOS (Ventura) should be possible.

**Comment by yktoo** [comment]
That's a bit of a surprise for me. Does your Mac OS have GTK3 installed?

As I've no experience developing for Mac OS, I'm not sure how the resource location issue is to be tackled.

The only reference in the code to `/usr/share` is related to i18n, the rest of the app is basically relying on GTK for picking up and rendering the correct resource. So could you provide a clue as to what kind of problems you experience?

**Comment by LordMyschkin** [comment]
I tried to mkdir an icons directory in /usr/share and than 
sudo cp -r resources/icons/* /usr/share/icons/
but his does not work because of "read only filesystem"-Error - seems this location is not possible .
It seems I have GTK3 installed, I have no idea how - I installed go via homebrew.
So the windows do render like
![grafik](https://github.com/yktoo/ymuse/assets/11705882/d13684ad-5a8e-43c0-828b-7efa1d5cd31d)

**Comment by yktoo** [comment]
Unfortunately I don't have any Mac OS machine to play with. But according to this [docpage](https://wiki.gnome.org/Projects/GTK/OSX/Bundling), you can try building an app bundle using `gtk-mac-bundler`, which is supposed to get everything right for running the app.

**Comment by LordMyschkin** [comment]
Although at very first sight, I do not get where to get the resources into that bundler, I'll give it a try - it's too temtping to not try it...
