### ISSUE TITLE
Icon suggestion

### ISSUE THREAD

**Issue by mrzapp** [yktoo/ymuse#78]
Hey @yktoo, thank you for this great app, I use it all the time!

May I suggest an icon design that communicates "muse" and "audio player" a bit more? It's just a very early sketch, but I'm thinking something like this:

| Base | Brown | Blue | Grey | 
| --- | --- | --- | --- |
| ![ymuse](https://github.com/yktoo/ymuse/assets/2747428/a6222c46-40c8-41b4-aca2-af386cbfdd05) | ![ymuse-brown](https://github.com/yktoo/ymuse/assets/2747428/52a017ad-eba6-429b-84b1-7e98bc648cdb) | ![ymuse-blue](https://github.com/yktoo/ymuse/assets/2747428/2646923c-6d7d-4bbf-baed-e23303362214) | ![ymuse-grey](https://github.com/yktoo/ymuse/assets/2747428/c510ea44-b047-4c3b-b010-ff51a7bebbcf) |

Or perhaps without the circle:

| Base | Brown | Blue | Grey |
| --- | --- | --- | --- |
| ![ymuse-nocircle](https://github.com/yktoo/ymuse/assets/2747428/4dcc2109-73fb-4b14-9767-8baf3a2e9e06) | ![ymuse-nocircle-brown](https://github.com/yktoo/ymuse/assets/2747428/b1226a92-c35b-4f8d-85d2-a609ac2af6bd) | ![ymuse-nocircle-blue](https://github.com/yktoo/ymuse/assets/2747428/f6b83d3d-8e02-4a71-9e0f-236f2ae75050) | ![ymuse-nocircle-grey](https://github.com/yktoo/ymuse/assets/2747428/4621712d-f662-49c5-80f5-0330bf922b92) |

Looks natural on the app grid, I reckon:
![image](https://github.com/yktoo/ymuse/assets/2747428/cad08efa-1491-4f08-93cb-822cdf10de4c)

**Comment by mrzapp** [comment]
@yktoo Aah, I see. I just think it's rather important that the icon communicates what the app does, in addition to its name. The current icon doesn't give me any idea what Ymuse is meant to do. I'll think about a way to incorporate that Y, so the whole name is represented.

**Comment by mrzapp** [comment]
Or maybe something in between:

| Base | Blue | Brown | Grey |
| --- | --- | --- | --- |
| ![ymuse](https://github.com/yktoo/ymuse/assets/2747428/c7842ce2-2915-424e-a459-ddf2472a8d50) | ... | ... | ... |

**Comment by yktoo** [comment]
Hey @mrzapp, thanks for your work! These last ones look interesting, two points:
* Can the muse be made a bit more feminine? :smile: 
* Perhaps a touch of colour? Maybe it's my own thing but these look pretty monochrome to me...

**Comment by mrzapp** [comment]
Good feedback, I'll give it a shot

**Comment by mrzapp** [comment]
First attempt at colouring. I assumed that what you meant by "feminine" was "less Greek", so i Germanified her a bit :D

![ymuse-colour2](https://github.com/yktoo/ymuse/assets/2747428/9351ec1b-b5d3-4f7a-ab19-0fb14dd931d2)

**Comment by yktoo** [comment]
I personally find the "A" brunette variant quite good.

**Comment by mrzapp** [comment]
@yktoo Me too. I'll polish it some more towards a final rendering.

**Comment by mrzapp** [comment]
@yktoo This is my first bid for a final rendering. Any thoughts?

![ymuse-colour-soft](https://github.com/yktoo/ymuse/assets/2747428/3a05bef8-dc2c-48e7-830a-6cfdc5b05154)

**Comment by yktoo** [comment]
Thanks @mrzapp! I like the palette and the image. My two cents:
* The underlying triangle in the previous version had sharp edges and I liked that better. The latest one is sleek but for me it doesn't really read as something related to "play"
* I also liked the gap between the triangle and the "Y" in the previous version, I believe it made the "Y" more discernible:
![image](https://github.com/yktoo/ymuse/assets/1675911/18db08cb-0755-46c0-ac5a-28eb8c35f86a)

**Comment by mrzapp** [comment]
Something like this (corners sharper, but still with a tiny rounding on them)?

| 32 | 64 | 128 |
| --- | --- | --- |
| <img alt="ymuse-colour-soft" width="32" src="https://github.com/yktoo/ymuse/assets/2747428/340a9a24-35f4-458a-8747-145f6dc61cff"> | <img alt="ymuse-colour-soft" width="64" src="https://github.com/yktoo/ymuse/assets/2747428/340a9a24-35f4-458a-8747-145f6dc61cff"> | <img alt="ymuse-colour-soft" width="128" src="https://github.com/yktoo/ymuse/assets/2747428/340a9a24-35f4-458a-8747-145f6dc61cff"> |

**Comment by yktoo** [comment]
Yes, I quite like it!

**Comment by mrzapp** [comment]
@yktoo alright, it's yours then :) I'll make a pull request
