### ISSUE TITLE
Respect environment variables MPD_HOST, MPD_PORT

### ISSUE THREAD

**Issue by zhelezov** [yktoo/ymuse#8]
Title should be self-explanatory. It crashes on me because of waiting on connection to localhost but I have no MPD running there.

**Comment by yktoo** [comment]
Okay. What seems reasonable to me is filling the Ymuse's MPD preferences from these two vars on the first run and ignoring them once the values are provided. This would allow for using the environment for defaults, which is a common practice IMO.

**Comment by zhelezov** [comment]
Or ignore them completely from the start if you want so, but exit from the loop polling for a connection and signal the error so we have the chance to enter the preferences. Thanks for sharing the project btw. I hope it receives the love of the community and we get  a nice mature GUI client for MPD that doesn't get abandoned too soon. I am a [Cantata](https://github.com/cdrummond/cantata) user on the desktop but I would love to see an alternative.

Good luck with your project and thanks again!

**Comment by yktoo** [comment]
Thanks. These are two separate issues in my view. On wrong connection params the app does start but isn't responding, I've created #9 for that.
