### ISSUE TITLE
All icons are missing

### ISSUE THREAD

**Issue by oredaze** [yktoo/ymuse#81]
I used the binary package on Void linux. Program works fine, but all icons (besides folder and volume) are missing and instead have a red error placeholder instead. I use ubuntu's Yaru icon theme, but same happens with others.

**Comment by yktoo** [comment]
What DE are you using? I guess the reason for the missing icons is it uses some non-standard icon location.

**Comment by oredaze** [comment]
Openbox.
The archive did not have icons, besides application ones, but I just saw the repo has some, I am going to try with those and see. Wait a second.

**Comment by oredaze** [comment]
Yes, the scalable icons in the repo work fine. I suggest you put them in the binary package release.
Thanks for the nice software.

**Comment by yktoo** [comment]
Which binary package do you mean? As far as I'm concerned, `.rpm` and `.deb` ship all the icons, the same with snap and flatpak.

**Comment by oredaze** [comment]
ymuse_0.22_linux_amd64.tar.gz

**Comment by yktoo** [comment]
Good point, fixing it.
