### ISSUE TITLE
No dark theme

### ISSUE THREAD

**Issue by KnowledegAndAction** [yktoo/ymuse#83]
Linux Mint 21.2 Cinnamon
ymuse v0.22 

The default theme is light, and there is no option to switch to dark mode.

**Comment by yktoo** [comment]
There's no setting for choosing a theme, that's right. Ymuse is a GTK application that follows the system theme, so it'll be rendered in a dark theme if one is active.
![image](https://github.com/yktoo/ymuse/assets/1675911/59395eb3-47d6-46a9-8a17-fa31b5a43082)
