### ISSUE TITLE
constant crashing on wayland (sway)

### ISSUE THREAD

**Issue by quantenzitrone** [yktoo/ymuse#85]
After a while of using ymuse on sway, ymuse always crashes with one of these error messages:
```
Gdk-Message: 11:31:02.995: Error reading events from display: Connection reset by peer
```
```
Gdk-Message: 11:27:02.652: Error flushing display: Broken pipe
```
```
Gdk-Message: 11:39:33.166: Lost connection to Wayland compositor.
```
mostly the first one

I can't really figure out what is happening there, using the `-vv` flag doesn't help, as it only prints what I am doing before suddenly crashing with one of the above error messages and no additional information.
The crashing does not seem to depend on a single reproducible action, but rather on clicking around furiously, changing title, skipping around in the song or moving around in the library.
There are also no coredumps.

If you know anything on how to get more information on the problem, I'll be willing to help.

**Comment by yktoo** [comment]
I doubt it has to do anything with Ymuse. The message `Error reading events from display: Connection reset by peer` suggests there's some connectivity issue. Do you connect to your display via network? Do you observe similar issues with other apps? What are your distro, WM and DE?

**Comment by quantenzitrone** [comment]
I'm using SwayFX on NixOS, normal internal laptop display.
I had similar crashes with other applications too, but none as often as ymuse.
Now that I think of it, it could also be an NVIDIA issue, since I am using the absolutely proprietary drivers, which are not officially supported by sway, for good reasons.

**Comment by yktoo** [comment]
Well yes, that sounds like asking for problems :laughing:

Also, if I google your messages, it seems like quite a common problem.

**Comment by quantenzitrone** [comment]
Ok I'll close this then
maybe if anyone can get more intel on what is going on we can try to fix it
but until then: blame it on nvidia
