### ISSUE TITLE
Library performance slow

### ISSUE THREAD

**Issue by sashaaaaaaaaa** [yktoo/ymuse#92]
With a large library (120000+ tracks), when I choose "Artists" or "Albums" under Library the program freezes for a good few minutes before it shows anything.

**Comment by yktoo** [comment]
The rendering speed is limited by the (pretty crappy) performance of GTK3, Ymuse itself adds almost no overhead. This is unfortunately not fixable on our side.

**Comment by sashaaaaaaaaa** [comment]
ooh i see sorry for the false issue
